### ISSUE TITLE
Create icon for UniFriend

### ISSUE THREAD

**Issue by DomNook** [Gruppe-1B/IS-114-1-Gruppearbeid#74]

**Comment by Surprisebacon** [comment]
![Unifriend](https://user-images.githubusercontent.com/50771130/140041752-7c0683c2-1352-417a-adce-7633ffca69c1.png)

**Comment by Surprisebacon** [comment]
![Unifriend](https://user-images.githubusercontent.com/50771130/140042702-23fcecad-4315-4487-bae7-d008bef749f0.png)
